all:
        @echo "Compiling APEX Simulator"
        javac ApexProject1/src/ApexMain.java
        @echo "Compilation Successful\n"

        @echo "Starting Execution..."
        java ApexProject1/src/ApexMain $(filePath)

